nameSpace: default
apiVersion: v1
replicas: 3
name: web
image: ikubernetes/myapp:v2
service:
  type: NodePort
  name: web
  port: 80
  targetPort: 80
  nodePort: 30080
  host: sestci.xyz
  ingressName: ingress-myapp
