apiVersion: extensions/v1beta1          #api版本
kind: Ingress           #清单类型
metadata:                       #元数据
  name: {{ .Values.service.ingressName }}    #ingress的名称
  namespace: {{ .Values.nameSpace }}     #所属名称空间
  annotations:           #注解信息
    kubernetes.io/ingress.class: "nginx"
spec:      #规格
  rules:   #定义后端转发的规则
  - host: {{ .Values.service.host }}    #通过域名进行转发
    http:
      paths:
      - path:       #配置访问路径，如果通过url进行转发，需要修改；空默认为访问的路径为"/"
        backend:    #配置后端服务
          serviceName: {{ .Values.name }}
          servicePort: {{ .Values.service.port }}
